# Generated by Django 4.2 on 2023-04-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='course',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='middle_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='nin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='staff_id',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
