# Generated by Django 4.2 on 2023-04-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clientmodel_course_clientmodel_middle_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='owner',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
