# Generated by Django 4.2 on 2023-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_clientmodel_phone_number_alter_clientmodel_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='grade_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
