# Generated by Django 4.2 on 2023-04-28 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_clientmodel_grade_level_alter_clientmodel_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='course',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
